# Generated by Django 5.1.3 on 2024-12-04 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automates_app', '0002_remove_post_user_remove_userprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_username', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin_access_token', models.TextField(blank=True, null=True)),
                ('github_username', models.CharField(blank=True, max_length=150, null=True)),
                ('github_access_token', models.TextField(blank=True, null=True)),
                ('x_username', models.CharField(blank=True, max_length=150, null=True)),
                ('x_access_token', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('generated_text', models.TextField()),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='automates_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_link', models.URLField(max_length=255)),
                ('user_description', models.TextField()),
                ('post_audience', models.CharField(max_length=50)),
                ('post_tone', models.CharField(max_length=50)),
                ('post_style', models.CharField(max_length=50)),
                ('post_hashtags', models.TextField()),
                ('ai_prompt', models.TextField()),
                ('generated_description', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('time_uploaded', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='automates_app.userprofile')),
            ],
        ),
    ]
