# Generated by Django 4.1 on 2024-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automates_app', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='audience_textbox',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='style_textbox',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='tone_textbox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
