# Generated by Django 4.1 on 2024-12-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automates_app', '0008_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='generated_text',
            field=models.TextField(default='no description'),
        ),
    ]
