# Generated by Django 4.1 on 2024-12-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automates_app', '0009_draft_generated_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='generated_text',
        ),
    ]
